// client/src/components/Footer.vue
<template>
    <span class="base" :style="{
        color: $store.getters.getTheme.font_color,
        backgroundColor: $store.getters.getTheme.top_bar_bg_color,
    }">
        Made with
        <FontAwesomeIcon icon="laugh"/>
        by <b>DSC-ASU (jo)</b> &nbsp;
        <a class="linkedin" href="https://www.linkedin.com/company/dscasu/" target="_blank">
            <FontAwesomeIcon :icon="{prefix: 'fab', iconName: 'linkedin'}" class="linkedin"/>
        </a> &nbsp;
        <a class="facebook" href="https://web.facebook.com/DSCASU" target="_blank">
            <FontAwesomeIcon :icon="{prefix: 'fab', iconName: 'facebook'}" class="facebook"/>
        </a> &nbsp;

        <a class="dsc" href="https://dsc.community.dev/applied-science-private-university/" target="_blank">
                <FontAwesomeIcon :icon="{prefix: 'fab', iconName: 'google'}"/>
        </a> &nbsp;
        •
        <a href="https://github.com/mbaraa/dsc_logo_generator" target="_blank">
            <FontAwesomeIcon icon="code"/>
            <FontAwesomeIcon :icon="{prefix: 'fab', iconName: 'github'}"/>
        </a> •
    </span>
</template>

<script>
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {faLaugh, faCode} from "@fortawesome/free-solid-svg-icons";
import {faFacebook, faGithub, faLinkedin, faGoogle} from "@fortawesome/free-brands-svg-icons";
import {library} from "@fortawesome/fontawesome-svg-core";
// font awesome
library.add(faFacebook, faGithub, faLinkedin, faLaugh, faCode, faGoogle);


export default {
    name: "Footer",
    components: {
        FontAwesomeIcon
    },
}
</script>

<style scoped>

a {
    color: #ff00ff;
    text-decoration: unset;
}

.linkedin {
    color: #0e76a8;
}

.facebook {
    color: #00acee;
}

.dsc {
    color: #FFFFFF;
}

.base {
    font-family: ProductSans;
    position: fixed;
    bottom: 0;
    margin: auto;
    width: 100%;
    text-align: center;
}
</style>

// client/src/components/Footer.svelte
<script lang="ts">
  import Fa from "svelte-fa/src/fa.svelte";
  import { faLaugh } from "@fortawesome/free-solid-svg-icons";
import LinkWithPhoto from "./LinkWithPhoto.svelte";
</script>

<div class="fixed bottom-0 border-t-[1px] border-t-[#F6F6F6] w-full h-[45px]">
  <div
    class="absolute bottom-[12px] px-[24px] text-center w-full flex justify-between text-[13px]"
  >
    <label class="text-[#888888] font-black">
      Made with <Fa class="inline" icon={faLaugh} /> By GDSC-ASU (JO)
    </label>

    <div> 
        <LinkWithPhoto link="https://gdsc.community.dev/applied-science-private-university/" imagePath="/images/google.png" />
        <LinkWithPhoto link="https://www.linkedin.com/company/66952281/admin/" imagePath="/images/linkedin.png" />
        <LinkWithPhoto link="https://www.facebook.com/DSCASU" imagePath="/images/facebook.png" />
        <LinkWithPhoto link="https://github.com/mbaraa/dsc_logo_generator" imagePath="/images/github.png" />
    </div>
  </div>
</div>
